/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Invoices {
  amount_cents: Int8;
  created_at: Generated<Timestamp>;
  currency: string;
  id: Generated<string>;
  plan_code: string;
  product: string;
  status: Generated<string>;
  tenant_id: string;
}

export interface Outbox {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  failed_at: Timestamp | null;
  id: Generated<string>;
  last_error: string | null;
  payload: Buffer;
  published_at: Timestamp | null;
  subject: string;
  traceparent: string | null;
}

export interface Subscriptions {
  canceled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  current_period_end: Timestamp | null;
  id: Generated<string>;
  plan_code: string;
  product: string;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  invoices: Invoices;
  outbox: Outbox;
  subscriptions: Subscriptions;
}
