/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Memberships {
  created_at: Generated<Timestamp>;
  role: Generated<string>;
  tenant_id: string;
  user_id: string;
}

export interface Outbox {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  failed_at: Timestamp | null;
  id: Generated<string>;
  last_error: string | null;
  payload: Buffer;
  published_at: Timestamp | null;
  subject: string;
  traceparent: string | null;
}

export interface PasswordResetTokens {
  claimed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: Buffer;
  user_id: string;
}

export interface Sessions {
  absolute_expires_at: Timestamp;
  expires_at: Timestamp;
  family_id: string;
  id: Generated<string>;
  ip: string | null;
  issued_at: Generated<Timestamp>;
  replaced_by: string | null;
  revoked_at: Timestamp | null;
  tenant_id: string | null;
  token_hash: Buffer;
  user_agent: string | null;
  user_id: string;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  slug: string | null;
}

export interface Users {
  ban_expires_at: Timestamp | null;
  ban_reason: string | null;
  banned: Generated<boolean>;
  created_at: Generated<Timestamp>;
  email: string;
  email_verified_at: Timestamp | null;
  id: Generated<string>;
  must_change_password: Generated<boolean>;
  name: string | null;
  password_changed_at: Generated<Timestamp>;
  password_hash: string;
  role: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  memberships: Memberships;
  outbox: Outbox;
  password_reset_tokens: PasswordResetTokens;
  sessions: Sessions;
  tenants: Tenants;
  users: Users;
}
