#!/usr/bin/env bash
set -euo pipefail

# One-shot deploy entry point. Idempotent — re-run for every change.
#
#   1. Loads infra/.env (the single source of truth).
#   2. Generates any blank secrets and saves them back to .env.
#   3. Runs `tofu apply` for the Cloudflare tunnel + DNS + ingress.
#   4. Writes infra/kamal/.kamal/secrets-common from the env.
#   5. Runs `host-init` on first run (when the `deploy` user doesn't exist).
#   6. Runs `kamal-first-deploy.sh` on first run, or `kamal deploy` otherwise.

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO_ROOT/infra/.env"
TOFU_DIR="$REPO_ROOT/infra/tofu"
KAMAL_DIR="$REPO_ROOT/infra/kamal"
SECRETS_FILE="$KAMAL_DIR/.kamal/secrets-common"

# ── 0. Pre-flight: required tools on PATH ────────────────────────────────────

# Gem-installed binaries (kamal) land in Ruby's gem bin dir which isn't on
# Homebrew Ruby's default PATH. Auto-add so `kamal` resolves.
if ! command -v kamal >/dev/null 2>&1; then
  for gem_bin in /opt/homebrew/lib/ruby/gems/*/bin "$HOME/.gem/ruby/"*/bin; do
    [[ -d "$gem_bin" ]] && export PATH="$gem_bin:$PATH"
  done
fi

need() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing tool: $1. Install: $2" >&2
    exit 1
  }
}
need tofu   "brew install opentofu"
need kamal  "sudo gem install kamal -N  (kamal is a Ruby gem, not a brew formula)"
need ssh    "(comes with macOS)"
need docker "OrbStack or Docker Desktop"

# Docker daemon must respond. Kamal talks to it locally even when builder.remote
# is set (for orchestrating buildx + the deploy commands).
if ! docker info >/dev/null 2>&1; then
  echo "Docker daemon not responding. Start OrbStack (open -a OrbStack) or Docker Desktop, then re-run." >&2
  exit 1
fi

# ── 1. Load infra/.env ───────────────────────────────────────────────────────

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing $ENV_FILE — create it: cp infra/.env.example infra/.env" >&2
  exit 1
fi

set -a; source "$ENV_FILE"; set +a

# ── 2. Generate missing secrets, save back to .env ───────────────────────────

# macOS sed and GNU sed disagree on `-i` syntax; this works on both via a
# zero-length backup extension that we then delete.
write_back() {
  local key="$1" value="$2"
  if grep -q "^${key}=" "$ENV_FILE"; then
    sed -i.bak "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
    rm -f "$ENV_FILE.bak"
  else
    echo "${key}=${value}" >> "$ENV_FILE"
  fi
  printf '%s' "$value"
}

gen_if_empty() {
  local var="$1" generator="$2"
  if [[ -z "${!var:-}" ]]; then
    local value; value=$(eval "$generator")
    export "$var=$(write_back "$var" "$value")"
    echo "[deploy] generated $var (saved to .env)"
  fi
}

gen_if_empty STATE_PASSPHRASE      'openssl rand -base64 24'
gen_if_empty BETTER_AUTH_SECRET    'openssl rand -base64 32'
gen_if_empty POSTGRES_PASSWORD     'openssl rand -hex 32'
gen_if_empty MINIO_ROOT_PASSWORD   'openssl rand -hex 32'
gen_if_empty REGISTRY_PASSWORD     'openssl rand -hex 16'   # local registry doesn't enforce auth but kamal requires the field

: "${CLOUDFLARE_ACCOUNT_ID:?missing in infra/.env}"
: "${CLOUDFLARE_ZONE_ID:?missing in infra/.env}"
: "${CLOUDFLARE_API_TOKEN:?missing in infra/.env}"
: "${PUBLIC_HOSTNAME:?missing in infra/.env}"
: "${ONPREM_HOST:?missing in infra/.env}"
: "${BOOTSTRAP_USER:?missing in infra/.env}"

# Derived
ASSETS_HOSTNAME="assets.${PUBLIC_HOSTNAME#*.}"
KAMAL_BUILD_CONTEXT="$REPO_ROOT"        # absolute path — deploy.yml reads this for builder.context
export ONPREM_HOST PUBLIC_HOSTNAME ASSETS_HOSTNAME KAMAL_BUILD_CONTEXT

# ── 3. Tofu apply ────────────────────────────────────────────────────────────

export TF_VAR_account_id="$CLOUDFLARE_ACCOUNT_ID"
export TF_VAR_zone_id="$CLOUDFLARE_ZONE_ID"
export TF_VAR_cloudflare_api_token="$CLOUDFLARE_API_TOKEN"
export TF_VAR_state_passphrase="$STATE_PASSPHRASE"
export TF_VAR_public_hostname="$PUBLIC_HOSTNAME"

echo "[deploy] tofu apply (Cloudflare tunnel + DNS)"
(cd "$TOFU_DIR" && tofu init -upgrade -input=false >/dev/null && tofu apply -auto-approve)

TUNNEL_TOKEN=$(cd "$TOFU_DIR" && tofu output -raw tunnel_token)
export TUNNEL_TOKEN

# ── 4. Write Kamal secrets ───────────────────────────────────────────────────

mkdir -p "$(dirname "$SECRETS_FILE")"
umask 077
cat > "$SECRETS_FILE" <<EOF
# Auto-generated by infra/deploy.sh — DO NOT EDIT by hand.
# Source of truth: infra/.env.
REGISTRY_PASSWORD=$REGISTRY_PASSWORD
TUNNEL_TOKEN=$TUNNEL_TOKEN
BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@meta-menu-postgres:5432/metamenu
REDIS_URL=redis://meta-menu-redis:6379
MINIO_ROOT_USER=$MINIO_ROOT_USER
MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
S3_ACCESS_KEY=$MINIO_ROOT_USER
S3_SECRET_KEY=$MINIO_ROOT_PASSWORD
EOF

# ── 5. Host-init (only if `deploy` user can't yet log in) ────────────────────

if ssh -o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new \
       "deploy@$ONPREM_HOST" 'true' 2>/dev/null; then
  echo "[deploy] deploy@$ONPREM_HOST already reachable, skipping host-init"
else
  echo "[deploy] running host-init (you'll be prompted for $BOOTSTRAP_USER's sudo password)"
  HOST="$ONPREM_HOST" SUDO_USER="$BOOTSTRAP_USER" bash "$REPO_ROOT/scripts/host-init.sh"
fi

# ── 5b. Ensure deploy user is in docker group (idempotent every run) ─────────
# kamal server bootstrap installs Docker but doesn't grant non-root access.
# `groupadd -f` is no-op if the group exists; `usermod -aG` is no-op if the
# user is already in the group. Runs every `make deploy` — cheap insurance
# against drift or a host that was bootstrapped before this script existed.
echo "[deploy] ensuring deploy user is in docker group"
ssh -o BatchMode=yes "deploy@$ONPREM_HOST" \
    'sudo groupadd -f docker && sudo usermod -aG docker deploy'

# ── 5c. Ensure local registry container is running on the box ────────────────
# Started directly via docker (not as a Kamal accessory) because
# `kamal accessory boot registry` would docker-login to this registry before
# it exists. The registry binds to 0.0.0.0:5000 — buildx running on the box
# can't reach 127.0.0.1:5000 (different netns) and Kamal only sets buildx
# --network=host for `localhost:*` registries (which we can't use because
# Kamal would SSH-forward those back to the Mac). So we expose on the LAN
# and tell Docker daemon to trust the LAN IP as an insecure registry.
echo "[deploy] ensuring local registry:3 is running on the box (LAN:5000)"
ssh -o BatchMode=yes "deploy@$ONPREM_HOST" "ONPREM_HOST=$ONPREM_HOST bash -s" <<'REMOTE'
set -euo pipefail

# Configure docker daemon to trust the LAN-bound registry as insecure (HTTP).
# Idempotent: only restart docker if daemon.json was actually changed.
DAEMON_JSON=/etc/docker/daemon.json
DESIRED="{\"insecure-registries\":[\"$ONPREM_HOST:5000\"]}"
if ! sudo test -f "$DAEMON_JSON" || [ "$(sudo cat "$DAEMON_JSON" 2>/dev/null)" != "$DESIRED" ]; then
  sudo mkdir -p /etc/docker
  echo "$DESIRED" | sudo tee "$DAEMON_JSON" >/dev/null
  sudo systemctl restart docker
  sleep 3
fi

# Recreate the registry container so port binding picks up any changes
# (older runs may have bound it to 127.0.0.1 — wrong for our case).
sg docker -c '
  docker rm -f kamal-registry 2>/dev/null || true
  docker run -d \
    --name kamal-registry \
    --restart always \
    -p 5000:5000 \
    -v kamal-registry-data:/var/lib/registry \
    registry:3 >/dev/null
'
REMOTE

# ── 5d. Pre-create the buildx builder with insecure-registry config ──────────
# Kamal will reuse an existing builder if name + endpoint match. Pre-creating
# is the only way to inject insecure-registry trust since Kamal hard-codes
# the `docker buildx create` command without a hook for buildkitd config.
# See: /opt/homebrew/lib/ruby/gems/*/gems/kamal-*/lib/kamal/commands/builder/remote.rb
BUILDER_NAME="kamal-remote-ssh---deploy-${ONPREM_HOST//./-}"
REMOTE_CONTEXT="${BUILDER_NAME}-context"
BUILDKITD_CFG=$(mktemp -t buildkitd.XXXXXX.toml)
trap 'rm -f "$BUILDKITD_CFG"' EXIT

cat > "$BUILDKITD_CFG" <<EOF
[registry."${ONPREM_HOST}:5000"]
  http = true
  insecure = true
EOF

echo "[deploy] pre-creating buildx builder with insecure-registry config"
docker context inspect "$REMOTE_CONTEXT" >/dev/null 2>&1 || \
  docker context create "$REMOTE_CONTEXT" --docker "host=ssh://deploy@$ONPREM_HOST" >/dev/null

# Recreate every run so any drift in BUILDKITD_CFG is picked up.
docker buildx inspect "$BUILDER_NAME" >/dev/null 2>&1 && docker buildx rm "$BUILDER_NAME" >/dev/null
docker buildx create \
  --name "$BUILDER_NAME" \
  --driver docker-container \
  --buildkitd-config "$BUILDKITD_CFG" \
  "$REMOTE_CONTEXT" >/dev/null

# ── 6. First-deploy or normal deploy ─────────────────────────────────────────
# Detect first-deploy via the presence of the `kamal-proxy` container on the
# box. That container is created by `kamal setup` and never by `kamal deploy`
# alone — so it's a reliable "has setup run successfully" signal. Checking
# accessories is unreliable: they may have been booted by a previous failed
# `kamal setup` run, but env files won't have been pushed yet.
cd "$KAMAL_DIR"
if ssh -o BatchMode=yes "deploy@$ONPREM_HOST" 'docker inspect kamal-proxy' >/dev/null 2>&1; then
  echo "[deploy] kamal deploy"
  kamal deploy
else
  echo "[deploy] first-time bootstrap"
  bash "$REPO_ROOT/scripts/kamal-first-deploy.sh"
fi

echo
echo "Done. App: https://$PUBLIC_HOSTNAME"
