package main

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// runtime_local.go writes the local-dev .env file consumed by the
// `apps/web` container (and `bun run dev` when running outside
// Docker). The companion to runtime_docker.go: Stage-4-shaped logic,
// but pointed at the local Docker stack instead of Hetzner.
//
// The surface URL env-var NAMES (CORE_BASE_URL, NEXT_PUBLIC_MENU_URL,
// CORE_TRUSTED_ORIGINS, etc.) come from topology.go::surfaces — same
// source of truth the live runtime + tunnel.tf consume. The VALUES
// today all collapse to http://localhost:3000 because Playwright +
// the existing dev workflow assume that one origin; the *.localhost
// host-based dispatch path is opt-in and lives behind a future PR
// that also updates playwright.config.ts and proxy.ts's path-based
// fallback.
//
// Non-surface entries (database URLs, S3, OTel, CORE_SECRET, etc.)
// stay hand-written here — they're infra plumbing, not topology.

const (
	devLocalBaseURL = "http://localhost:3000"
	devCoreSecretLen = 48
)

// writeDevEnv (re)generates apps/web/.env. Idempotent — safe to call
// every dev-stack invocation. Reads CORE_SECRET from .env.local if
// the operator has copied it there for session persistence (see
// docs/dev.md § Environment files); otherwise mints a fresh one.
//
// envPath / envLocalPath are absolute. s3Port matches the host port
// of dev/docker-compose.yml's s3mock service.
func writeDevEnv(envPath, envLocalPath string, s3Port int) error {
	coreSecret, err := readOrMintCoreSecret(envLocalPath)
	if err != nil {
		return fmt.Errorf("core_secret: %w", err)
	}

	s3Endpoint := fmt.Sprintf("http://infra-s3mock:%d", s3Port)
	s3PublicURL := fmt.Sprintf("http://localhost:%d/iedora-assets", s3Port)
	otelAuth := base64.StdEncoding.EncodeToString([]byte("dev@iedora.local:Password1!"))

	// Build the env map. Surface URL entries derive from topology;
	// values currently collapse to devLocalBaseURL — see file header.
	env := map[string]string{
		"NODE_ENV":                "development",
		"NEXT_TELEMETRY_DISABLED": "1",
		"GIT_SHA":                 "dev",
		"HOST_NAME":               "localhost",

		"IEDORA_BOOTSTRAP_ADMIN_EMAILS": "eduardoferdcarvalho@gmail.com",

		"CORE_DATABASE_URL": "postgres://postgres:Password1!@infra-postgres:5432/core",
		"MENU_DATABASE_URL": "postgres://postgres:Password1!@infra-postgres:5432/menu",

		"CORE_SECRET":        coreSecret,
		"CORE_COOKIE_DOMAIN": "localhost",

		"S3_ACCESS_KEY":       "test",
		"S3_SECRET_KEY":       "test",
		"S3_BUCKET":           "iedora-assets",
		"S3_REGION":           "us-east-1",
		"S3_ENDPOINT":         s3Endpoint,
		"S3_PUBLIC_URL":       s3PublicURL,
		"S3_FORCE_PATH_STYLE": "true",

		"OTEL_EXPORTER_OTLP_ENDPOINT": "http://infra-openobserve:5080/api/default",
		"OTEL_EXPORTER_OTLP_HEADERS":  "Authorization=Basic%20" + otelAuth,
	}

	// Surface URL envs — names from topology, values are local.
	// NEXT_PUBLIC_CORE_URL keeps a /core path suffix so the
	// path-based fallback in apps/web/src/proxy.ts works while
	// every surface still binds to localhost:3000.
	for _, s := range surfaces {
		if s.publicURLEnv != "" {
			env[s.publicURLEnv] = devLocalBaseURL
		}
		if s.nextPublicEnv != "" {
			env[s.nextPublicEnv] = devLocalBaseURL
		}
	}
	if _, ok := env["NEXT_PUBLIC_CORE_URL"]; ok {
		env["NEXT_PUBLIC_CORE_URL"] = devLocalBaseURL + "/core"
	}
	env[trustedOriginsEnv] = devLocalBaseURL

	return writeEnvFile(envPath, env)
}

func writeEnvFile(path string, env map[string]string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# AUTO-GENERATED by `iedora local env` (called from bin/dev-stack).\n")
	b.WriteString("# Source of truth: infra/deploy/cmd/iedora/{topology,runtime_local}.go.\n")
	b.WriteString("# Overrides go in apps/web/.env.local (gitignored, higher precedence).\n")
	for _, k := range keys {
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(env[k])
		b.WriteByte('\n')
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// readOrMintCoreSecret looks for a CORE_SECRET line in .env.local and
// returns its value if present; otherwise mints a fresh 48-byte
// base64 secret. .env.local is owned by the operator — we never
// write to it.
func readOrMintCoreSecret(envLocalPath string) (string, error) {
	if data, err := os.ReadFile(envLocalPath); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			if v, ok := strings.CutPrefix(line, "CORE_SECRET="); ok {
				v = strings.TrimSpace(v)
				if v != "" {
					return v, nil
				}
			}
		}
	}
	buf := make([]byte, devCoreSecretLen)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(buf), nil
}
