/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditLog {
  action: string;
  actor_id: string | null;
  actor_type: string | null;
  changed_fields: Json | null;
  entity_id: string | null;
  entity_type: string | null;
  id: Generated<string>;
  ip: string | null;
  metadata: Generated<Json>;
  new_data: Json | null;
  occurred_at: Generated<Timestamp>;
  old_data: Json | null;
  outcome: Generated<string>;
  source: string | null;
  tenant_id: string | null;
  user_agent: string | null;
}

export interface InboxMessage {
  message_id: string;
  processed_at: Generated<Timestamp>;
  topic: string;
}

export interface DB {
  audit_log: AuditLog;
  inbox_message: InboxMessage;
}
