/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditLog {
  action: string;
  actor_id: string | null;
  actor_type: Generated<string>;
  at: Generated<Timestamp>;
  id: Generated<string>;
  ip: string | null;
  message_id: string | null;
  meta: Generated<Json>;
  outcome: Generated<string>;
  schema_version: Generated<number>;
  session_id: string | null;
  source: Generated<string>;
  target_id: string | null;
  target_type: string | null;
  tenant_id: string | null;
  trace_id: string | null;
  user_agent: string | null;
}

export interface DB {
  audit_log: AuditLog;
}
