package main

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"sort"
	"strings"
)

// writeMenuEnvFiles composes products/menu/.env from local-stack statics
// then writes excluded-service keys to .env.local as `<please_fill>`
// placeholders.
//
// All values here are well-known constants for the local stack — the
// menu image talks to `infra-postgres:5432`, `infra-openobserve:5080`,
// `infra-localstack:4566`. No Tofu output reads, no app-state outputs —
// the orchestrator owns the recipe end-to-end.
func writeMenuEnvFiles(envPath, envLocalPath string, selected []string) {
	env := composeMenuEnv(envLocalPath)

	excluded := excludedEnvKeys(selected)
	excludeSet := map[string]bool{}
	for _, k := range excluded {
		excludeSet[k] = true
	}
	envForFile := map[string]string{}
	for k, v := range env {
		if !excludeSet[k] {
			envForFile[k] = v
		}
	}
	writeEnvFile(envPath, envForFile)
	writeEnvLocal(envLocalPath, excluded)
}

// composeMenuEnv returns the full menu env map for the local stack.
// `envLocalPath` is consulted only to recover an existing IEDORA_CORE_SECRET
// across orchestrator runs (so sign-ins survive a restart).
func composeMenuEnv(envLocalPath string) map[string]string {
	authSecret := stableAuthSecret(envLocalPath)

	return map[string]string{
		// Static literals — true for the dev container topology.
		"NODE_ENV":                    "development",
		"NEXT_TELEMETRY_DISABLED":     "1",
		"S3_REGION":                   "us-east-1",
		"S3_ACCESS_KEY":               "test",
		"S3_SECRET_KEY":               "test",
		"S3_BUCKET":                   "iedora-assets",
		"HOST_NAME":                   "localhost",
		"GIT_SHA":                     "dev",
		"MENU_PUBLIC_URL":             "http://localhost:3000",
		"IEDORA_CORE_BASE_URL":        "http://localhost:3000",
		"IEDORA_CORE_TRUSTED_ORIGINS": "http://localhost:3000",
		"IEDORA_CORE_COOKIE_DOMAIN":   "localhost",
		"IEDORA_CORE_SECRET":          authSecret,
		"NEXT_PUBLIC_CORE_URL":        "http://localhost:3000/core",
		"S3_PUBLIC_URL":               "http://localhost:4566/iedora-assets",
		"DATABASE_URL":                "postgres://postgres:Password1!@infra-postgres:5432/menu",
		"CORE_DATABASE_URL":           "postgres://postgres:Password1!@infra-postgres:5432/core",
		"S3_ENDPOINT":                 "http://infra-localstack:4566",
		"OTEL_EXPORTER_OTLP_ENDPOINT": "http://infra-openobserve:5080/api/default",
		// Same Basic-auth header shape as prod (OO root_user_email +
		// password, base64'd, URL-escaped). Hardcoded for dev.
		"OTEL_EXPORTER_OTLP_HEADERS": "Authorization=Basic%20" + base64.StdEncoding.EncodeToString([]byte("dev@iedora.local:Password1!")),
	}
}

// stableAuthSecret keeps IEDORA_CORE_SECRET stable across orchestrator
// runs so existing sign-ins survive a restart. If `.env.local` already
// pins one, reuse it; otherwise mint 48 bytes and persist via the
// .env.local writer downstream.
func stableAuthSecret(envLocalPath string) string {
	existing := parseEnvLocal(envLocalPath)
	if v, ok := existing["IEDORA_CORE_SECRET"]; ok && v != "" && v != placeholderValue {
		return v
	}
	buf := make([]byte, 48)
	if _, err := rand.Read(buf); err != nil {
		fail("mint auth secret: %v", err)
	}
	return base64.RawStdEncoding.EncodeToString(buf)
}

// writeEnvFile emits the .env file with a stable key order. Includes a
// header explaining the file is auto-generated.
func writeEnvFile(path string, env map[string]string) {
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# AUTO-GENERATED by `go run ./dev/cmd/local-stack`.\n")
	b.WriteString("# Composed from local-stack statics; the dev orchestrator owns the recipe.\n")
	b.WriteString("# Overrides live in `.env.local` (gitignored).\n\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s=%s\n", k, env[k])
	}
	if err := os.WriteFile(path, []byte(b.String()), envFileMode); err != nil {
		fail("write %s: %v", path, err)
	}
}

// writeEnvLocal emits .env.local with `<please_fill>` placeholders for
// excluded services. Preserves operator overrides that aren't placeholders
// (so re-running `go run ./dev/cmd/local-stack` doesn't wipe edits).
func writeEnvLocal(path string, excluded []string) {
	existing := parseEnvLocal(path)

	if len(excluded) == 0 && len(existing) == 0 {
		_ = os.Remove(path)
		return
	}

	// Drop any prior placeholder for a key that's no longer excluded.
	excludeSet := map[string]bool{}
	for _, k := range excluded {
		excludeSet[k] = true
	}
	for k, v := range existing {
		if v == placeholderValue && !excludeSet[k] {
			delete(existing, k)
		}
	}
	for _, k := range excluded {
		if _, ok := existing[k]; !ok {
			existing[k] = placeholderValue
		}
	}

	keys := make([]string, 0, len(existing))
	for k := range existing {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Operator overrides for products/menu/.env. Edit any KEY=value\n")
	b.WriteString("# pair to override what `go run ./dev/cmd/local-stack` composes. Keys set to\n")
	b.WriteString("# `<please_fill>` are placeholders for services skipped via\n")
	b.WriteString("# --except — set them to a remote URL.\n\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s=%s\n", k, existing[k])
	}
	if err := os.WriteFile(path, []byte(b.String()), envFileMode); err != nil {
		fail("write %s: %v", path, err)
	}
}

func parseEnvLocal(path string) map[string]string {
	out := map[string]string{}
	body, err := os.ReadFile(path)
	if err != nil {
		return out
	}
	for _, line := range strings.Split(string(body), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		out[strings.TrimSpace(k)] = strings.TrimSpace(v)
	}
	return out
}

// warnEnvLocalState surfaces a leading warning when .env.local has
// operator-overridden keys for a service that's in the active selection.
func warnEnvLocalState(envLocalPath string, selected []string) {
	existing := parseEnvLocal(envLocalPath)
	if len(existing) == 0 {
		return
	}
	excludeSet := map[string]bool{}
	for _, k := range excludedEnvKeys(selected) {
		excludeSet[k] = true
	}
	var shadowing []string
	for k, v := range existing {
		v = strings.TrimSpace(v)
		if v == "" || v == placeholderValue {
			continue
		}
		if !excludeSet[k] {
			shadowing = append(shadowing, k)
		}
	}
	if len(shadowing) > 0 {
		sort.Strings(shadowing)
		fmt.Printf("%s ⚠ .env.local shadows %d auto-composed key(s): %s\n",
			logPrefix, len(shadowing), strings.Join(shadowing, ", "))
	}
}
