-- 0002_target_index.sql — index the per-target activity feed.
--
-- The admin restaurant view loads a single restaurant's trail via
-- `forTarget` → `WHERE target_id = $1 ORDER BY (at, id) DESC LIMIT n`. The
-- 0001 indexes are all tenant_id-leading, so that query had no usable index
-- and fell back to a full scan + sort of audit_log on every view — cost grows
-- with the whole table, not the restaurant's history. This mirrors the tenant
-- feed index but keyed by target, giving an ordered index scan that reads only
-- the rows for that target. Created on the partitioned parent so it cascades
-- to every partition.
CREATE INDEX IF NOT EXISTS audit_log_target_at_idx ON audit_log (target_id, at DESC, id DESC);
