/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface EmailDelivery {
  id: Generated<string>;
  at: Generated<Timestamp>;
  source: string;
  tenant_id: string | null;
  to_addr: string;
  subject: string;
  status: Generated<string>;
  error: string | null;
  message_id: string | null;
}

export interface InboxMessage {
  message_id: string;
  processed_at: Generated<Timestamp>;
  topic: string;
}

export interface DB {
  email_delivery: EmailDelivery;
  inbox_message: InboxMessage;
}
