import { betterAuth } from 'better-auth'
import { drizzleAdapter } from 'better-auth/adapters/drizzle'
import { admin } from 'better-auth/plugins/admin'
import { jwt } from 'better-auth/plugins/jwt'
import { organization } from 'better-auth/plugins/organization'
import { oauthProvider } from '@better-auth/oauth-provider'
import type { PgDatabase, PgQueryResultHKT } from 'drizzle-orm/pg-core'
import { db } from '@/shared/db/client'
import * as schema from '@/shared/db/schema'
import { env } from '@/shared/env'

type AuthDb = PgDatabase<PgQueryResultHKT, typeof schema>

/**
 * Every model Better Auth touches at runtime, given Genkan's plugin set.
 * Exported so tests can assert completeness against a known-good list — if
 * you enable a Better Auth plugin or storage option that adds a new model,
 * register it here AND mirror it on `BA_MODELS` so the integration test
 * catches the wiring gap before it ships.
 */
export const BA_MODELS = {
  user: schema.user,
  session: schema.session,
  account: schema.account,
  verification: schema.verification,
  organization: schema.organization,
  member: schema.member,
  invitation: schema.invitation,
  rateLimit: schema.rateLimit,
  // jwt plugin — JWKS for signing OIDC tokens.
  jwks: schema.jwks,
  // oauth-provider plugin tables. Generated by `bun run auth:generate`.
  oauthClient: schema.oauthClient,
  oauthAccessToken: schema.oauthAccessToken,
  oauthRefreshToken: schema.oauthRefreshToken,
  oauthConsent: schema.oauthConsent,
} as const

/**
 * Pre-registered first-party clients. Each tuple in TRUSTED_CLIENTS is
 *
 *   client_id|client_secret|redirect_uri_1,redirect_uri_2
 *
 * with one tuple per line / comma-separated outer pieces. We mark every
 * entry `skipConsent=true` so signed-in users coming from menu (or future
 * first-party products) don't see the consent screen — by definition the
 * iedora estate has already consented to its own apps.
 */
function parseTrustedClients(raw: string | undefined) {
  if (!raw) return [] as const
  return raw
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      const [clientId, clientSecret, redirectUris] = line.split('|')
      if (!clientId || !clientSecret || !redirectUris) {
        throw new Error(
          `Invalid TRUSTED_CLIENTS entry — expected "id|secret|uri1,uri2", got: ${line}`,
        )
      }
      return {
        client_id: clientId,
        client_secret: clientSecret,
        redirect_uris: redirectUris.split(',').map((u) => u.trim()),
        // Auto-grant scopes — first-party only.
        skipConsent: true,
        // Full OIDC + the iedora product scopes.
        scope: 'openid profile email offline_access menu org:read org:admin',
      } as const
    })
}

const TRUSTED_CLIENTS = parseTrustedClients(env.TRUSTED_CLIENTS)

/**
 * Factory. Production uses the singleton at the bottom; tests construct
 * their own instance pointed at a PGLite db to exercise the real adapter
 * wiring (e.g. catch "model X not found in schema object" before deploy).
 */
export function makeAuth(database: AuthDb) {
  return betterAuth({
    baseURL: env.BETTER_AUTH_URL,
    database: drizzleAdapter(database, {
      provider: 'pg',
      schema: BA_MODELS,
    }),
    trustedOrigins: env.TRUSTED_ORIGINS,
    emailAndPassword: {
      enabled: true,
    },
    rateLimit: {
      enabled: process.env.DISABLE_AUTH_RATE_LIMIT !== 'true',
      storage: 'database',
    },
    // Platform-admin field on the user. Users default to "user"; flipping a
    // row to "admin" gates access to /admin. The admin plugin reads this.
    user: {
      additionalFields: {
        role: {
          type: 'string',
          required: false,
          defaultValue: 'user',
          input: false, // not settable through public signup
        },
      },
    },
    advanced: {
      // No more crossSubDomainCookies — products federate via OIDC now. Each
      // app keeps its own host-scoped cookie; the OAuth handshake carries
      // identity between hosts.
      ipAddress: {
        ipAddressHeaders: ['cf-connecting-ip'],
        ipv6Subnet: 64,
      },
    },
    plugins: [
      // Better Auth 1.6.11 flipped the verification default; we don't ship
      // email verification yet so leaving the flag at the new default would
      // silently reject every invite. Flip when the email-sender lands.
      organization({ requireEmailVerificationOnInvitation: false }),

      // Platform-admin APIs: list/create/disable users, list sessions, etc.
      // Routes are gated server-side by user.role==='admin'.
      admin(),

      // JWT signing for OAuth tokens. The oauth-provider plugin requires
      // this — id_tokens and access_tokens are signed RS256 with a key
      // material managed by the JWT plugin. Exposes /.well-known/jwks.json
      // so any OIDC client (.NET, Go, Node, etc.) verifies tokens via JWKS.
      jwt(),

      // OAuth 2.1 + OIDC provider. Genkan becomes the canonical IdP for the
      // iedora estate. Menu and future products (incl. .NET APIs) federate
      // here. Standard `.well-known/openid-configuration` + JWKS so any
      // OIDC-compliant client validates tokens without bespoke code.
      oauthProvider({
        loginPage: '/login',
        consentPage: '/consent',
        // Supported scopes. `openid profile email offline_access` are the
        // OIDC standards; the rest are iedora-specific product/role grants.
        scopes: [
          'openid',
          'profile',
          'email',
          'offline_access',
          'menu', // access to the menu product
          'org:read', // can read user's organizations + members
          'org:admin', // can create/update/delete organizations
        ],
        // Pre-register first-party clients here (env-driven so secrets stay
        // in BWS). Dynamic clients (third-party) register via the
        // `/oauth2/register` endpoint and are stored in oauth_application.
        trustedClients: TRUSTED_CLIENTS,
        // Auto-cache trusted clients on first lookup so the hot path is in
        // memory, not DB.
        cacheTrustedClients: true,
        // Sign-up landing within the OIDC `prompt=create` flow.
        signup: {
          page: '/signup',
        },
        // Genkan claims to expose in the userinfo response — organizations
        // + role go here so OAuth clients (menu, .NET APIs) read identity
        // membership from the JWT, not from a sibling DB.
        getAdditionalUserInfoClaim: async (
          user: { id: string; role?: string },
          scopes: string[],
        ) => {
          const claims: Record<string, unknown> = {}
          // `org:read` = include orgs the user is a member of.
          if (scopes.includes('org:read')) {
            // Lazy-load to avoid a static cycle through plugins/auth.
            const { listUserOrganizations } = await import(
              '@/features/auth/use-cases/list-user-organizations'
            )
            claims.organizations = await listUserOrganizations(user.id)
          }
          // Always include platform role — needed by genkan's own /admin gate.
          const u = user as typeof user & { role?: string }
          if (u.role) claims.role = u.role
          return claims
        },
      }),
    ],
  })
}

export const auth = makeAuth(db)

export type Session = typeof auth.$Infer.Session
