/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AiGenerations {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  tenant_id: string;
}

export interface Categories {
  created_at: Generated<Timestamp>;
  description: string | null;
  description_i18n: Json | null;
  id: Generated<string>;
  menu_id: string;
  name: string;
  name_i18n: Json | null;
  position: Generated<number>;
  restaurant_id: string;
  translations_synced_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface DailyView {
  count: Generated<number>;
  day: string;
  language: string;
  restaurant_id: string;
  tenant_id: string;
}

export interface Inbox {
  consumer_group: string;
  message_id: string;
  processed_at: Generated<Timestamp>;
}

export interface Items {
  available: Generated<boolean>;
  category_id: string;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  description: string | null;
  description_i18n: Json | null;
  id: Generated<string>;
  image_url: string | null;
  name: string;
  name_i18n: Json | null;
  position: Generated<number>;
  price_cents: number;
  restaurant_id: string;
  tags: Generated<string[]>;
  translations_synced_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  variants: Json | null;
}

export interface Menus {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  description: string | null;
  description_i18n: Json | null;
  id: Generated<string>;
  name: string;
  name_i18n: Json | null;
  position: Generated<number>;
  restaurant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Outbox {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  failed_at: Timestamp | null;
  id: Generated<string>;
  last_error: string | null;
  payload: Buffer;
  published_at: Timestamp | null;
  subject: string;
  traceparent: string | null;
}

export interface QrCodes {
  bound_at: Timestamp | null;
  code: string;
  created_at: Generated<Timestamp>;
  label: string | null;
  restaurant_id: string | null;
}

export interface RateLimitEvents {
  key: string;
  occurred_at: Generated<Timestamp>;
}

export interface Restaurants {
  banner_url: string | null;
  created_at: Generated<Timestamp>;
  default_currency: Generated<string>;
  default_language: Generated<string>;
  description: string | null;
  description_i18n: Json | null;
  id: Generated<string>;
  logo_url: string | null;
  name: string;
  onboarding_completed_at: Timestamp | null;
  slug: string;
  supported_languages: Generated<string[]>;
  tenant_id: string;
  theme: Json | null;
  updated_at: Generated<Timestamp>;
}

export interface ViewSeen {
  hour_bucket: string;
  restaurant_id: string;
  seen_at: Generated<Timestamp>;
  visitor_id: string;
}

export interface DB {
  ai_generations: AiGenerations;
  categories: Categories;
  daily_view: DailyView;
  inbox: Inbox;
  items: Items;
  menus: Menus;
  outbox: Outbox;
  qr_codes: QrCodes;
  rate_limit_events: RateLimitEvents;
  restaurants: Restaurants;
  view_seen: ViewSeen;
}
